name: eeg
description: "脑电系统"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2

# 执行dart run flutter_launcher_icons替换图标
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "logo/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "logo/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "logo/logo.png"
    icon_size: 256

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.3
  easy_localization: ^3.0.7
  flutter_smart_dialog: ^4.9.8+5
  provider: ^6.1.2
  url_launcher: ^6.3.1
  dio: ^5.7.0
  window_manager: ^0.4.3
  system_theme: ^3.1.2
  flutter_acrylic: ^1.1.4
  connectivity_plus: ^6.1.1
  crypto: ^3.0.6
  # 获取版本号
  package_info_plus: ^8.1.2
  event_bus: ^2.0.1
  # https://pub.dev/packages/isolate_easy_pool
  isolate_easy_pool: ^0.0.8
  # https://github.com/flutterchina/flukit
  #  flukit: ^3.0.1
  # https://bdlukaa.github.io/fluent_ui/
  fluent_ui: ^4.9.2
  #https://flutter-shadcn-ui.mariuti.com/
  shadcn_ui: ^0.22.5
  # 视频播放
  media_kit: ^1.1.5
  media_kit_video: ^1.2.5
  media_kit_libs_video: ^1.0.5
  data_table_2: ^2.6.0
  file_picker: ^9.2.1

flutter:
  uses-material-design: true
  fonts:
    - family: 'SiyuanLightFont'
      fonts:
        - asset: fonts/Siyuan-Light.otf
  assets:
    - assets/
    - images/background/
    - images/loading/
    - logo/logo.png
    - locals/